### ISSUE TITLE
[Meta] List of Raiden Service Bundle ToDos to be done before Release

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-service-bundle#129]
Here is a todo list of things we have to do and nice to have before the release:

### Todos
- [x] introduce prefix `transport.${SERVER_NAME}` for matrix server
- [x] [remove lexographical order of server list in room ensurer](https://github.com/raiden-network/raiden-service-bundle/issues/128)
- [x] [update and review readme](https://github.com/raiden-network/raiden-service-bundle/issues/124)
- [x] show testing commands
- [x] [Create `known_servers."release_name".yml`](https://github.com/raiden-network/raiden-service-bundle/issues/109)
- [x] Increase power levels of admin of new provider in broadcast rooms upon a new provider join.

- [x] [ReadMe Todos](https://github.com/raiden-network/raiden-service-bundle/issues/139)
- [x] Decide on how to handle known server file (#131)
- [x] Readme links
    - [x] Update the Etherscan link to the Service Registry contract under "Registering a RSB"
    - [x] current release link
    - [x] git clone command
    - [x] introduce Upgrade section

### Nice to have
- [ ] [Run services in docker with lower privileges](https://github.com/raiden-network/raiden-service-bundle/issues/97)
- [ ] [Adjust Postgres parameters to system ](https://github.com/raiden-network/raiden-service-bundle/issues/45)
- [ ] [create a testing script](https://github.com/raiden-network/raiden-service-bundle/issues/126)

**Comment by fredo** [comment]
closed due to new release
