### ISSUE TITLE
Add image build automation

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-service-bundle#36]
# Problem Description

For the `raiden-service-bundle` releases (see also #34), we should automate image creation via CI and remove the `build...` steps from `docker-compose.yaml`.

This 
- allows fine-grained control for the images in use (use tagged versions in `docker-compose.yaml`)
  - `build/db`
  - `build/synapse`
  - `build/well-known-server`
- minimizes the setup time for a raiden service bundle operator

### ToDo
- [x] Create dockerhub repositor(y/ies) for the above mentioned images
  - for single repository, we could abuse image-tags for the different images, i.e.
    - `raidennetwork/raiden-service-bundle:db-2019.10.1`
    - `raidennetwork/raiden-service-bundle:synapse-2019.10.1`
    - `raidennetwork/raiden-service-bundle:well-known-server-2019.10.1`
- [x] If we don't want that, we need to define version tagging for the build targets
  - tags could follow `raiden-transport` / `raiden-service-bundle` release tags
    - `raidennetwork/raiden-transport-db:2019.10.1`, ...
  - tags could define their own versions
    - `raidennetwork/raiden-transport-db:9r1`, ...
- [x] Add CI to the repository
- [x] Add building, tagging and pushing for the above mentioned images to CI
- [x] Use `image: raidennetwork/<image_name>:<tag>` instead of `build:...` in `docker-compose.yaml`
